### ISSUE TITLE
Cursor centered between tags

### ISSUE THREAD

**Issue by Wikunia** [Matlal/brackets-HTML-Tag-Autocomplete#1]
If I write `<ul` and press enter I don't want that my cursor is after the `</ul>` normally.
I want to have it between `<ul>` and `</ul>`.

**Comment by Matlal** [comment]
This is issue is fixed with  #2  !

**Comment by Wikunia** [comment]
Btw I think you might wanna check out this extension if you're interested in the functionality.
https://github.com/emmetio/brackets-emmet

**Comment by Matlal** [comment]
That looks interesting!

**Comment by Matlal** [comment]
Sorry, I made a mistake sending you that invite and trying to give you contributor privileges. This is a school project that we are currently working on and I'm still new to Github.

**Comment by Wikunia** [comment]
No worries mate. Keep on with your project and welcome on GitHub.
Maybe you find some stuff that might be nice which isn't included in emmet then you can build it into your project. You can write me a mail if you have questions about brackets extensions. I worked on several of my own and know Brackets is sometimes a bit weird and the docs aren't the best. 

Have fun with your project!
